### ISSUE TITLE
XKCD password generator

### ISSUE THREAD

**Issue by That-Dude** [MacPass/MacPass#958] opened 2019-07-20 15:26 UTC
Generate secure but memorable passwords using the XKCD method, exactly like this:

https://correcthorsebatterystaple.net/

**Comment by kud** [comment] 2019-07-23 09:33
related: https://github.com/MacPass/MacPass/issues/856

**Comment by mstarke** [comment] 2019-11-04 15:14
Duplicate of #313

**Closed by mstarke** 2019-11-04 15:14 UTC
Labels: Duplicate
