### ISSUE TITLE
Merge/Synchronise Databases

### ISSUE THREAD

**Issue by clnhlzmn** [MacPass/MacPass#786] opened 2018-05-01 12:32 UTC
This isn't really an issue. Please point me in the right direction if there is a better place to post this. I am wondering if there is a more thorough explanation of how the "Merge/Synchronise Databases" feature works. I am familiar with KeePass 2.38 on Windows. There I can have a "master" and "slave" copy of my database file with the master being the copy kept on my cloud storage and the slave copy being kept locally. KeePass opens the slave, and on a save it checks the master to see if there are any newer changes and updates both copies appropriately without losing data (as I understand it). KeePass synchronization with cloud storage described [here](https://keepass.info/help/kb/trigger_examples.html#dbsync).

With MacPass, from what I can tell, the "Merge Changes" option in the File Handling section of MacPass preferences is what controls MacPass's version of this synchronization behavior. What I can't tell is exactly what this option is doing and if it's really equivalent to the functionality that KeePass offers. 

Could someone please explain this to me or point me to an existing explanation please?

-Colin

**Comment by mstarke** [comment] 2018-05-02 06:59
MacPass as well as KeePass are able to synchronise databases. This is a core feature for both applications an works the same way. The details can be found here: https://keepass.info/help/v2/sync.html

What you are describing is an advanced system using triggers. Triggers are not present in MacPass and thus the process described as cloud backup is not possible with MacPass on its own. I have not looked into adding Triggers to MacPass but since this might be a feature worth implementing it should be considered.

What you can do is just use the a database in the cloud as a single source. If you have multiple clients accessing the file at the same time all of them need to be able to synchronise changes otherwise you risk data loss.

**Comment by clnhlzmn** [comment] 2018-05-02 12:10
Thanks for the info. It looks like the article on synchronization is talking about two database files. In the case that I'm opening my database from my cloud storage directly (not using master-slave) then the two databases we're referring to are the copy on disk and the copy in MacPass's memory? If that's the case then the synchronization performed by MacPass is the process that makes sure no data is lost from either the in memory copy or the on disk copy (in the event of a save or the on disk copy changing)?

**Comment by clnhlzmn** [comment] 2018-05-03 11:56
Thank you very much. That answers all my questions.

**Comment by mstarke** [comment] 2018-09-05 07:01
Closing since the issue is resolved.

**Closed by mstarke** 2018-09-05 07:01 UTC
