### ISSUE TITLE
KeePassKit fails while running carthage bootstrap command

### ISSUE THREAD

**Issue by er3do** [MacPass/MacPass#795] opened 2018-05-23 10:09 UTC
**Describe the bug**
KeePassKit fails while running `carthage bootstrap --platform macOS` command

**To Reproduce**
1. Download MacPass sources: `git clone https://github.com/mstarke/MacPass --recursive
`
2. `cd MacPass`
3. Run `carthage bootstrap --platform macOS`
```
*** Building scheme "KeePassKit macOS" in KeePassKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /Users/dhomenok/Downloads/soft/MacPass/Carthage/Checkouts/KeePassKit/KeePassKit.xcodeproj -scheme KeePassKit\ macOS -configuration Release -derivedDataPath /Users/dhomenok/Library/Caches/org.carthage.CarthageKit/DerivedData/9.3.1_9E501/KeePassKit/1.12 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/g1/5zxqmymj11v_8_gdv14cnd2c0000gp/T/KeePassKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/dhomenok/Downloads/soft/MacPass/Carthage/Checkouts/KeePassKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/g1/5zxqmymj11v_8_gdv14cnd2c0000gp/T/carthage-xcodebuild.JyQowb.log
```

**Expected behavior**
Success message that all dependencies have been installed.

**Desktop (please complete the following information):**
 - macOS: 10.13.4
 - Xcode: 9.3.1
 - Homebrew 1.6.4

**Additional context**
Full log is attached
[carthage-xcodebuild.JyQowb.log](https://github.com/MacPass/MacPass/files/2030547/carthage-xcodebuild.JyQowb.log)

**Comment by mstarke** [comment] 2018-05-23 10:15
The error is generated in KissXML referencing some libxml headers. This might be a change in macOS 10.13 which KissXML hits.

**Comment by mstarke** [comment] 2018-05-23 10:21
The error does not occur on 10.12.

**Comment by er3do** [comment] 2018-05-23 12:55
fyi, The last time I was able to successfully build the dependencies on mac os 10.13.3

**Comment by mstarke** [comment] 2018-05-23 12:55
Moved to the correct project: https://github.com/MacPass/KeePassKit/issues/37

**Comment by mstarke** [comment] 2018-05-23 15:20
To clarify this is an Xcode 9.3 issue which cannot occur under 10.12 since 9.3 requires 10.13.

**Comment by na69an** [comment] 2018-06-01 17:40
I also have this issue.
Env:
- xcode: 9.4 (9F1027a)
- os: 10.13.4
- macports 2.5.0
- carthage 0.29.0

~/prj/MacPass $ carthage bootstrap --platform macOS
*** Checking out HNHUi at "1.4.2"
*** Checking out KeePassKit at "1.12"
*** Checking out Sparkle at "1.18.1"
*** xcodebuild output can be found in /var/folders/vm/966pgj1556z48k_wh7y6rchc0000gn/T/carthage-xcodebuild.IHsWwS.log
*** Downloading Sparkle.framework binary at "1.18.1"
*** Building scheme "HNHUi" in HNHUi.xcodeproj
*** Building scheme "KeePassKit macOS" in KeePassKit.xcodeproj
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project ~/prj/MacPass/Carthage/Checkouts/KeePassKit/KeePassKit.xcodeproj -scheme KeePassKit\ macOS -configuration Release -derivedDataPath ~/Library/Caches/org.carthage.CarthageKit/DerivedData/9.4_9F1027a/KeePassKit/1.12 ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/vm/966pgj1556z48k_wh7y6rchc0000gn/T/KeePassKit SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in ~/prj/MacPass/Carthage/Checkouts/KeePassKit)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/vm/966pgj1556z48k_wh7y6rchc0000gn/T/carthage-xcodebuild.IHsWwS.log

**Comment by mstarke** [comment] 2018-06-04 09:19
The issue is fixed in continuous and master by switching to a newer KissXML version. I waited a bit since I did not want to bring unnecessary swift dependencies into the project.

**Closed by mstarke** 2018-06-04 09:19 UTC
