### ISSUE TITLE
Hotkey Commad+Shift+E for new Entry not working

### ISSUE THREAD

**Issue by eporsche** [MacPass/MacPass#405] opened 2015-12-31 13:01 UTC
Minor Issue
Hotkey: Commad+Shift+E for new Entry does not work when the Symbol Area is hidden. Instead it opens Save As.

**Comment by mstarke** [comment] 2021-01-21 15:08
I'm closing this since I cannot reproduce the issue anymore.

**Closed by mstarke** 2021-01-21 15:08 UTC
Labels: Bug
