### ISSUE TITLE
Opening database do not focus any folder

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#812] opened 2018-07-11 09:19 UTC
No folder is selected when macpass is started.

**To Reproduce**
1. Start macpass
2. put your password
3. no folder is selected

**Expected behavior**
The root folder is selected like proposed in #443 (marked as fixed, but it doesn't seem to works)
Or the last open folder before closing macpass
Or an option to set the default view like in #424  

**Screenshots**
![screen shot 2018-07-11 at 11 14 01](https://user-images.githubusercontent.com/164074/42562403-f345b420-84fb-11e8-806f-d8652f0bae8e.png)

**Desktop (please complete the following information):**
 - macOS: 10.13.5
 - Version 0.7.3

**Comment by mstarke** [comment] 2018-07-11 10:10
As stated on many other UI related bugs - this is a regression in 10.13 which needs fixing

**Comment by mstarke** [comment] 2018-11-14 06:57
This regressed and is fixed in d6ea2830e9956e099ab62978e6b7e4a20a31ae1e
There's a problem here, since changing those value is not registerd as a change to the file so no autosave or request to change on close is popping up. That means no changes are stored unless something else is modified (e.g. an entry added) under normal read-only usage the selection will not be stored automatically via autosave only on manual save.

**Closed by mstarke** 2018-11-14 06:57 UTC
Labels: Bug, macOS 10.13
