### ISSUE TITLE
Show all passwords

### ISSUE THREAD

**Issue by chrismjspencer** [MacPass/MacPass#532] opened 2017-01-06 18:37 UTC
Macpass is the brilliant mac friendly alternative to keypass i've been looking for for months.... however its missing one feature...the ability to show all passwords in clear text in the middle window rather than opening each individually.

I use macpass to store passwords for a variety of systems, many airgapped networks etc, so need the ability to view and then type the password manually.

Could this be considered?

**Comment by luwadmin** [comment] 2017-07-22 16:41
Michael, I too would like to aks you for this enhancement, because I am no friend of "asterisk-itis", either. When I am the only one in the world to use my computer, nobody coming even close to peep over my shoulder, why should I be denied to see my own passwords in the clear? Makes no sense, does it? :)   Keep up the outstanding work, BTW

**Comment by mrglutton** [comment] 2018-01-10 09:19
Ditto. There should be an option, just like in a KeePass.

**Comment by nigellh** [comment] 2018-04-06 11:00
Yes please!!!!!

**Comment by djkelly99** [comment] 2019-11-14 14:26
I would also love to see this.  I know am using several very weak passwords but it's hard to see which ones unless I go through them all individually.

**Comment by CountCount** [comment] 2020-05-28 10:37
+1
I second this, this feature is also part of KeyPassXC which I used until it didn't work anymore with Catalina 10.15.4+.

**Comment by mstarke** [comment] 2021-02-08 20:18
Duplicate of #347

**Closed by mstarke** 2021-02-08 20:18 UTC
Labels: Enhancement
