### ISSUE TITLE
Regression: Big Sur: Title bar layout changed unintentionally

### ISSUE THREAD

**Issue by milosivanovic** [MacPass/MacPass#1130] opened 2021-01-03 10:13 UTC
In https://github.com/MacPass/MacPass/issues/1113#issuecomment-753462851, @mstarke stated that they did not change the layout, so this appears to be an accidental regression. Here is what it looks like on my machine (M1 MacBook Air):

**Version 0.7.12 (23610):**
<img width="1107" alt="Screen Shot 2021-01-03 at 11 09 56 PM" src="https://user-images.githubusercontent.com/1274505/103476247-e9957580-4e18-11eb-9ffc-83858d72ba24.png">

**Version 0.8-beta (20201231211202-continuous):**
<img width="1107" alt="Screen Shot 2021-01-03 at 11 10 07 PM" src="https://user-images.githubusercontent.com/1274505/103476248-ee5a2980-4e18-11eb-90b0-d9d0dd73f54b.png">

**Comment by georgesnow** [comment] 2021-01-03 11:59
Unless I am missing something in those screenshots. That's the new system layout for Big Sur for title bars (defined by macOS not MacPass). Maybe if markup the screenshots for what you mean?

**Comment by xrisk** [comment] 2021-01-03 12:58
So I’m not sure if this is a WONTFIX considering it is standard Big Sur design. But personally speaking I dislike it because it means that the search bar and so on aren’t visible unless the window is sufficiently wide.

I like to use MacPass as a small window and the new design basically breaks my workflow because I can’t access search.

New:
<img width="614" alt="Screen Shot 2021-01-03 at 6 23 55 PM" src="https://user-images.githubusercontent.com/10669859/103479084-2188c280-4df1-11eb-9b97-a21d69f7534e.png">

Old:
<img width="614" alt="Screen Shot 2021-01-03 at 6 23 14 PM" src="https://user-images.githubusercontent.com/10669859/103479085-23eb1c80-4df1-11eb-876e-07fdfb8b6770.png">

The old UI wasted much lesser space on small window sizes IMO, but again I can understand if this is a wontfix.

**Comment by georgesnow** [comment] 2021-01-03 13:05
Agreed. I heavily use search with smaller window. My plugin is based using the search box. I got believe there is improvement or maybe just personally rearranging the toolbar?

**Comment by mstarke** [comment] 2021-01-03 15:46
The search box in Big Sur should get reduced to a button if it does not fit. If this does not happen I might have to adopt newer APIs to make the toolbar useable again on small window sizes.

**Comment by mstarke** [comment] 2021-01-03 20:22
Mh. I did change the layout to use a fill size side bar which results in the toolbar being scaled down. I might have to dabble a bit with the arrangement. Also it's possible to allow for special items to be present in the side bar which is now missing since I have not made any changes there. Currently it looks looks like the layout for MacPass needs to stick with the "old style" toolbar design which is still possible in Big Sur…

**Comment by mstarke** [comment] 2021-01-04 15:15
I've changed the layout to be like it was before so search should work as before. I am a bit hesitant to keep it that way since I do like the "unified" look but if this reduced the usability then we have to stick to the "old" style.

**Comment by milosivanovic** [comment] 2021-01-05 04:37
Thanks @mstarke! I would say this is a good compromise for now. (Personally, I did prefer when the search bar was fully centered as it was right above the list of results, so the mouse only had to move up slightly to reach it, but that might just be my experience.)

**Version 0.8-beta (20210104150120-continuous):**
<img width="1097" alt="Screen Shot 2021-01-05 at 5 06 22 PM" src="https://user-images.githubusercontent.com/1274505/103605469-d0a3d600-4f78-11eb-81b8-405b76bcbd6b.png">

It's worth noting that the negative space created by the sidebar is a cause for concern, but as others have said this is the new Big Sur design. Just keep in mind that this doesn't mean every macOS application needs to look the same. Perhaps a more significant future redesign might be needed to make MacPass more suitable for the new Big Sur design, or alternatively you could attempt to decouple the sidebar from the top section to get rid of some of that wasted space.

As I was writing this I came up with an idea that makes search more fitting (that also addresses my personal gripe in the first sentence): Perhaps if we shift the "Title | Username | Password" header section down a row, and put the search bar in its place?
**Here's a quick mockup I made:**
<img width="1097" alt="Screen Shot 2021-01-05 at 5 06 22 PM" src="https://user-images.githubusercontent.com/1274505/103606824-452c4400-4f7c-11eb-9d5a-c83a609e616a.png">

What do you think?

**Comment by mstarke** [comment] 2021-01-05 13:34
The search box above the entry list was there on some very old releases but I did move it upward since I wanted to keep in line with the rest of macOS. Btw. If the finder window is too small on Catalina to display the search field it gets moved into the "search bar" below so this might be a solution for MacPass as well.

I think the best way currently is to remove all the left space by allowing the old style layout. And then we could move to a different more Big Sur like look which might involve some heavy modifications.

**Comment by mstarke** [comment] 2021-01-05 14:06
Todays continous release includes a revert to use the full size toolbar again. This shoulf fix all the regressions. As stated before, after this is out we can try to come up with a better layout and then re-work the toolbar to fit this new layout (including a useful search)

**Comment by xrisk** [comment] 2021-01-06 08:22
LGTM!

**Comment by mstarke** [comment] 2021-01-18 13:39
I'm closing this since the "old way" now works on Big Sur as well.

**Closed by mstarke** 2021-01-18 13:39 UTC
Labels: macOS 11

**Comment by mstarke** [comment] 2021-02-10 16:41
I'm opening issue  #1151 to discuss the changes necessary to make the new full size sidebar work with Big Sur. I've tested this now a bit and I do like the look a lot more but the wasted space is the biggest problem.
