### ISSUE TITLE
Custom icons lose color information on database save

### ISSUE THREAD

**Issue by alexbueschel** [MacPass/MacPass#779] opened 2018-04-06 16:18 UTC
I have a kind of strange issue with MacPass 0.7.3 possibly related to the update to macOS HighSierra 10.13.4 I did today. The issue also occurs also with the continuous build.

When I save the database, most of my custom icons "lost" some color information when I restart and reopen the database. Please see the attached screenshots for a better understanding of the issue:

Before:
![screen shot 2018-04-06 at 18 04 44](https://user-images.githubusercontent.com/13065401/38431758-971b280a-39c5-11e8-9583-5e815d883e6f.png)

After:
![screen shot 2018-04-06 at 18 03 50](https://user-images.githubusercontent.com/13065401/38431778-b1af1faa-39c5-11e8-9a68-4b7b13256a56.png)

Rollbacks to previous versions restores the information so this seems to be no display issue.

I've been able to reproduce the issue with a freshly created test database that I can provide if needed.

**Comment by mstarke** [comment] 2018-04-09 11:29
The icons are stored as PNG with no special consideration for the color profile and it seems to me that there are some changes in the underlying APIs that result in color shifts. I'll have to take a look into this when a 10.13 machine is available.

**Comment by mterron** [comment] 2018-06-27 09:56
I can confirm this behaviour and the bug must be in the load of the icons as they show up fine in KeePass.

**Comment by mstarke** [comment] 2018-08-16 06:39
The issue is the introduction of wrong gamma values and/or a miss-matching color profile. I've not come up with a solution for coco and might have to drop to libpng

**Comment by mstarke** [comment] 2018-08-21 17:03
The issue is fixed in master and deployed in continuous. MacPass will however not fix the wrongly stored gamma values. To fix the icons, you can open the file in KeePassXC and save it. Then the icons will look normal again in MacPass and will stay that way on save as well. I might have to come up with a tool to help fix this without having to rely on KeePassXC

**Closed by mstarke** 2018-08-21 17:03 UTC
Labels: Bug, macOS 10.13
