### ISSUE TITLE
No fallback if translation key is not present

### ISSUE THREAD

**Issue by cappert** [MacPass/MacPass#780] opened 2018-04-11 09:48 UTC
I use French MacOS and I get variable names instead of fallback strings where strings aren't in the localization file ([/fr.lproj/Localizable.strings](https://github.com/MacPass/MacPass/blob/master/MacPass/fr.lproj/Localizable.strings)).

See attached image for an example.

![localize bug example](https://user-images.githubusercontent.com/71031/38609389-38f1e34c-3d7e-11e8-894b-14e7da5a987e.png)

**Comment by mstarke** [comment] 2018-04-11 10:57
This works as intended. The identifiers are used internally and there is no fallback mechanism to a different language so missing translations will be displayed like this all the time. This is as it shoudl be, otherwise it would be quite hard to identify missing keys.

**Comment by cappert** [comment] 2018-04-11 13:13
>This works as intended. 
I assume you mean technically? I didn't look into your translation workflow yet, I don't know if the translation was submitted incomplete or if those keys were added later.

I'll try to translate the missing keys sometime but I still see it as an UX bug (I assume it's why you left the issue open)

**Comment by mstarke** [comment] 2018-04-11 13:47
I am quite sure the keys where added later. If you could get around and update the French localization and create a pull request that would be awesome. There's a section for contributing localizations in the Readme.

**Comment by mstarke** [comment] 2018-04-17 15:31
I can send you a current XLIFF for French. Might this help you in any way?

**Comment by cappert** [comment] 2018-04-17 15:36
First time doing this on MacOS so I'm not sure about the workflow.
I'd just have to open the .xliff file in XLIFFTool (I downloaded from the App Store) and translate, then export the strings?

**Comment by mstarke** [comment] 2018-04-17 16:15
You do not need to export anything. Just edit the .xliff file and hand it back to me so I can import it via Xcode.

**Comment by mstarke** [comment] 2018-12-06 07:31
Since this is working as expected I'm closing this.

**Closed by mstarke** 2018-12-06 07:31 UTC
