### ISSUE TITLE
unnecessary horizontal scrolling on listing view

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#777] opened 2018-04-03 16:56 UTC
The main listing view as an unnecessary horizontal scrolling. I had a hard time to do a screenshot showing the scrolling bar but on the following screenshot you can see an infinite empty table header:

![screen shot 2018-04-03 at 18 54 55](https://user-images.githubusercontent.com/164074/38263489-8d229c04-3770-11e8-830d-65a42a5ef180.png)

Same on every listing view.

**Comment by mstarke** [comment] 2018-04-04 09:34
Interesting bug. I have no idea how you ended up with this column. Can you try to remove the table columns from the preferences for and see if the error persists? **This will delete your settings for sorting and the order as well what columns are displayed but might fix the issue.**

```
defaults delete com.hicknhacksoftware.MacPass "NSTableView Columns v2 (null)"
defaults delete com.hicknhacksoftware.MacPass "NSTableView Columns v2 EntryTable"
defaults delete com.hicknhacksoftware.MacPass "NSTableView Sort Ordering v2 (null)"
defaults delete com.hicknhacksoftware.MacPass "NSTableView Sort Ordering v2 EntryTable"
defaults delete com.hicknhacksoftware.MacPass "NSTableView Supports v2 (null)"
defaults delete com.hicknhacksoftware.MacPass "NSTableView Supports v2 EntryTable"
```

**Comment by mstarke** [comment] 2018-04-05 10:04
My bad. Those commands are meant to be run separately.

Can you simply list all defaults via:

    defaults read com.hicknhacksoftware.MacPass

And see what of the mentioned keys is still present?

**Comment by mstarke** [comment] 2018-04-09 11:32
Did you have the time to look into this again?

**Comment by gagarine** [comment] 2018-04-11 13:09
Ok I did search the value and delete them. My pref was looking like that (minus the XXX) before I restarted MacPAss:

> ➜  Contents defaults read com.hicknhacksoftware.MacPass
> {
>     AutotypeMatchHost = 1;
>     AutotypeMatchTitle = 0;
>     AutotypeMatchURL = 1;
>     DoubleClickURLAction = 1;
>     EnableGlobalAutotype = 1;
>     EntrySearchFilterContext = <XXXXX>;
>     EntryTableSortDescriptors = <XXXXX>;
>     GlobalAutotypeKeyDataKey = <XXXX>;
>     LastDatabasePath = "file:///XXXXX.kdbx";
>     LockOnSleep = 0;
>     MPHTTPSettingsKeyShowMenuItem = 0;
>     MPHTTPSettingsKeyShowNotifications = 0;
>     NSNavLastRootDirectory = "~/XXXX";
>     NSNavPanelExpandedSizeForOpenMode = "{712, 448}";
>     NSNavPanelExpandedSizeForSaveMode = "{712, 542}";
>     NSNavPanelExpandedStateForSaveMode = 1;
>     "NSSplitView Subview Frames InspectorNotesSplitView" =     (
>         "0.000000, 0.000000, 353.000000, 616.000000, NO, NO",
>         "0.000000, 617.000000, 353.000000, 165.000000, NO, NO"
>     );
>     "NSSplitView Subview Frames SplitView" =     (
>         "0.000000, 0.000000, 150.000000, 832.000000, NO, NO",
>         "151.000000, 0.000000, 935.000000, 832.000000, NO, NO",
>         "1087.000000, 0.000000, 353.000000, 832.000000, NO, NO"
>     );
>     "NSToolbar Configuration MainWindowToolbar" =     {
>         "TB Display Mode" = 1;
>         "TB Icon Size Mode" = 1;
>         "TB Is Shown" = 1;
>         "TB Size Mode" = 1;
>     };
>     "NSWindow Frame DatabaseWindow" = "0 46 1440 854 0 0 1440 900 ";
>     RecentEntrySearches =     (
>      XXXX
>     );
>     SUEnableAutomaticChecks = 1;
>     SUHasLaunchedBefore = 1;
>     SULastCheckTime = "2018-04-10 19:34:27 +0000";
>     SUScheduledCheckInterval = 86400;
>     SUSendProfileInfo = 0;
> }

But still the same problem.

**Comment by mstarke** [comment] 2018-08-06 08:17
I cannot reproduce this behaviour on macOS 10.13.6

You seem to have moved the "Custom Order Column" to the end, this column does not have any title but it's there to allow for custom order by the user.

**Comment by gagarine** [comment] 2018-08-18 15:12
@mstarke oooh you right. I simply moved this "col with no name" at the beginning and it fixed the problem. Don't really understood how I can order stuff in a custom order but that's an other issue.

I guess we can close this issue. But perhaps you want to make it impossible to move this column at the end?

**Comment by mstarke** [comment] 2018-08-24 06:10
Disabling the Column to be moved might be a good ideas. I'm closing this to open a separate issue #823

**Closed by mstarke** 2018-08-24 06:10 UTC
Labels: Bug, macOS 10.13
