### ISSUE TITLE
Bug: Passwords are not deleted from clipboard

### ISSUE THREAD

**Issue by ssaring** [MacPass/MacPass#1019] opened 2019-12-23 20:00 UTC
**Describe the bug**
All entries copies to the clipboard needs to be removed after some seconds, as configured in the Preferences dialog. Unfortunately this does not happen, the copied usernames and password remain forever in the clipboard.

**To Reproduce**
1. Start MacPass and open an database.
2. Open the Preferences dialog, set Clipboard cleanup time to 10 seconds.
3. Select some database entry, copy the password from the Inspector pane by using right click on the password textfield.
4. Open a texteditor and paste the copied password immediately. 
5. Repeat the paste action after 60 seconds, the password has not been removed from the clipboard!

**Expected behavior**
The password copied to the clipboard needs to be deleted after 10 seconds.

**Screenshots**
Not needed.

**Desktop:**
 - macOS: 10.15.2
 - Version 0.7.10

**Additional context**
It doesn't matter what kind of copy action I'm using (shortcut, right click, in inspector, in list), the problem is always the same.

**Comment by mstarke** [comment] 2019-12-23 20:41
And another thing that broke with 10.15. I'll try to dig into this ASAP.

**Comment by georgesnow** [comment] 2020-01-13 16:49
@mstarke  I tested this on the latest commit and it is present there. I am running macOS 10.15.1. 

I tested 10 and 30 second options. I also noticed clear clipboard on quit isn't working. 

I also quit Alfred to be sure its clipboard manager isn't effecting it, but the issue is still present.

**Comment by georgesnow** [comment] 2020-01-13 17:50
@mstarke looks like clearContents only prepares the pasteboard for new contents. I tried in a test app with just:

`    [NSPasteboard.generalPasteboard clearContents];`

the clipboard never clears. however I added this and in MacPass's current build: 

```
    [NSPasteboard.generalPasteboard clearContents];
    [NSPasteboard.generalPasteboard setString:@"" forType:NSPasteboardTypeString];
```

not sure this a great fix, but it does provide a fix for leaving passwords in the clipboard

**Comment by georgesnow** [comment] 2020-01-21 15:08
also this seems directly related to Catalina. I tested on my other setup, which is running Mojave doesn't seem to have this issue.

**Comment by mstarke** [comment] 2020-01-22 09:18
I just tested this on macos 10.15.1 and cannot reproduce the issue.
I also just created a small app that just does ```[NSPasteboard.generalPasteboard clearContents];``` and it works as expected.

Do you have anything else watching or manipulating the clipboard?

**Comment by georgesnow** [comment] 2020-01-22 11:33
@mstarke yeah I have Alfred, but I quit out and confirmed it still happens. However, I tested on separate Catalina 10.15.1 machine with MacPass Cont and 0.7.10 (also with Alfred on/off). I can't reproduce on that machine. So there is something different. I will do some more investigating.

**Comment by georgesnow** [comment] 2020-01-22 14:28
alright well removing MacPass and reinstalling the new build with a reboot fixes it. so must have been something between the clipboard manager and MacPass. I am going to close my pull request cause I don't the issue any longer.

**Comment by mstarke** [comment] 2020-01-22 14:29
@ssaring Can you still reproduce the issue?

**Comment by ssaring** [comment] 2020-01-22 14:50
@mstarke Still having the same problem with MacPass version 0.7.10. Were there any code changes for this issue which need to be tested?

I'm not using any clipboard managers or similar tools such as Alfred. The only difference I can see is that I'm using macOS: 10.15.2 and you're using 10.15.1.

**Comment by mstarke** [comment] 2020-01-22 15:04
I did test this on 10.15.2 as well and the issue wasn't present there. There were no code changes from 0.7.9 to 0.7.10 that should affect this.

**Comment by ssaring** [comment] 2020-01-22 19:57
That's strange. The problem has existed for @georgesnow too (now not anymore), so it seems to occur in special conditions only.
IMHO the problem is too risky for ignoring and closing, but I have no idea how to reproduce that on your machines.

**Comment by georgesnow** [comment] 2020-01-22 20:07
And I was able to reproduce it on 10.15.1

**Comment by emikaadeo-git** [comment] 2020-01-26 09:28
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Start MacPass and open an database.
> 2. Open the Preferences dialog, set Clipboard cleanup time to 10 seconds.
> 3. Select some database entry, copy the password from the Inspector pane by using right click on the password textfield.
> 4. Open a texteditor and paste the copied password immediately.
> 5. Repeat the paste action after 60 seconds, the password has not been removed from the clipboard!
> 
Can't reproduce it on my machine.
After 10 seconds password was removed from Clipboard.

**Desktop:**

- macOS 10.15.2

- MacPass 0.7.10

**Comment by mstarke** [comment] 2020-01-26 10:34
@ssaring do you use Universal Clipboard?

**Comment by mstarke** [comment] 2020-01-26 10:38
Also could you try another KeePass client and test if it successfully clears the clipboard?

**Comment by ssaring** [comment] 2020-01-26 20:09
@mstarke No - I'm not using Universal Clipboard, it's disabled (checked right now).

I'm also using KeePassXC (version 2.5.3), the clipboard issue does not exists there. KeePassXC clears the clipboard properly after the configured time.

**Comment by ssaring** [comment] 2020-01-26 20:20
@mstarke I've just retried MacPass 0.7.10 once again today on macOS 10.15.2 (same machine). And for some reason the clipboard is now cleaned after 30 seconds. Don't ask my why it works now and not before - I've no idea what the difference is.

**Comment by mstarke** [comment] 2020-01-27 08:55
I'm going to close this for now and if you encounter it again, please re-open it or report a new issue. I thought I had encountered the issue as well when I first tried to reproduce it but since then have never been able to get it to show up again so I would file it under "mysteries worth uncovering"

**Closed by mstarke** 2020-01-27 08:55 UTC
Labels: Bug, Help Wanted!, macOS 10.15
