### ISSUE TITLE
Can't edit Window Associations in 0.7.3

### ISSUE THREAD

**Issue by astingengo** [MacPass/MacPass#850] opened 2018-11-20 23:42 UTC

**Comment by astingengo** [comment] 2018-11-20 23:43
The + button just add the `Window Title` but I can't edit it

**Comment by mstarke** [comment] 2018-11-21 08:03
Use the combo box below the list to edit the selected association. See #814

**Comment by mstarke** [comment] 2018-11-21 08:06
Use the combo box below the list to edit the window title. Duplicate of #817

**Closed** 2018-11-21 08:06 UTC
Labels: Duplicate

**Comment by astingengo** [comment] 2018-11-21 12:44
Sorry and thank you.
