### ISSUE TITLE
Autotype not working in macos 10.15 Catalina

### ISSUE THREAD

**Issue by revofever** [MacPass/MacPass#981] opened 2019-10-09 17:25 UTC
Both global autotype and clicking autotype in the app seem to have no effect in Catalina. This must be a permission issue? It was working fine in Mojave.

**Comment by n0lz** [comment] 2019-10-09 17:44
Same for me. Strangly it worked once shortly after the update. But since then no more.

**Comment by tramir** [comment] 2019-10-09 18:29
There is some work on this issue already (see here: https://github.com/MacPass/MacPass/issues/948), but it seems it's not entirely fixed yet.

**Comment by revofever** [comment] 2019-10-09 18:39
I updated to the continuous version, ran autotype doctor, and readded macpass to accessibility manually. It appears to be working for now.

**Comment by georgesnow** [comment] 2019-10-09 18:46
ok well that confirms what I thought. I think my other machine is running an older build of the continuous version

**Comment by tramir** [comment] 2019-10-09 18:47
I have the latest (Sept 17) version of the continuous version and I can't seem to make it work.

**Comment by georgesnow** [comment] 2019-10-09 18:49
you can use the tccutil and flush the settings, but that's going the drastic method of course

**Comment by tramir** [comment] 2019-10-09 18:51
I'm not sure if it's a settings issue, or which setting, because as I mentioned in the other thread MacPass seems to be able to read the window titles.

**Comment by georgesnow** [comment] 2019-10-09 18:52
so your not getting "null" in the window title match?

**Comment by tramir** [comment] 2019-10-09 18:53
Nope. If I activate Global Autotype in a window for which there's no match, I get a "no match" notification with the correct window title.

**Comment by orestesgaolin** [comment] 2019-10-15 10:46
It seems that MacPass doesn't have access to titles of all the other windows.

**Comment by peps1969** [comment] 2019-10-15 11:33
This issue is a duplicate of the following one:
https://github.com/MacPass/MacPass/issues/948
I guess it could be closed.

**Comment by xor-gate** [comment] 2019-11-01 21:36
For me it works fine with Chrome + Url in title plugin. On safari it doesn't work without tweaking.

**Comment by georgesnow** [comment] 2019-11-25 18:02
@mstarke this has some info about screen recording etc..not sure if will be helpful, but I thought. would share:

https://mjtsai.com/blog/2019/11/22/detecting-screen-recording-permission-on-catalina/

**Comment by mstarke** [comment] 2019-11-25 18:23
Thank you. I‘ve found Craig’s solution on Stackoverflow the other day and will use it to update my not-so-nice fix for 0.7.11

**Comment by mstarke** [comment] 2020-02-12 09:16
I would consider this closed for now as it seems to work for most users without issues

**Closed by mstarke** 2020-02-12 09:16 UTC
