### ISSUE TITLE
New entry is focused on first element after searching

### ISSUE THREAD

**Issue by olbrew** [MacPass/MacPass#985] opened 2019-10-17 17:00 UTC
Duplicates of #156 #239 and similar but since they were already closed and this is reproducible only in a specific state I thought I'd log a new one. If you'd rather I commented under the closed issues I'll do it!

## To reproduce
1. Do a search
2. Press CMD(⌘)+N or the button to create a new entry

## What happens
The entry is created but the text input is focused on the first entry in the current list.

## What should happen
The entry is created and the text input is focused on the new entry

Awesome tool btw! Thank you very much for making using Keepass on Mac a joy! :).

**Comment by mstarke** [comment] 2019-11-26 13:35
The issue is a tad more complicated. The search is still present but the results are hidden and the group with the newly created entry is selected.

I would consider the first solution to actually exit the search.

**Comment by olbrew** [comment] 2020-01-28 17:37
Yes, more specifically it always selects the Title of the first entry in the folder you were searching in. I have some folders with many entries where it's not immediately clear that a new entry was created if it wasn't selected in the first place. I'll then go look for an item with title `New Entry` to edit it as I wanted.

**Comment by mstarke** [comment] 2021-11-02 09:24
The issue is fixed in the current master since the group selection now gets removed when search is started.
This disables the creation of entries. It might not be the best way to solve this but I need to re-write the selection system and things like this should get fixed along the way.

**Closed** 2021-11-02 09:25 UTC
Labels: Bug
