### ISSUE TITLE
[Feature Request] Change group of multiple objects via drag and drop at once

### ISSUE THREAD

**Issue by Sh4pe** [MacPass/MacPass#839] opened 2018-10-05 10:59 UTC
You can change the group an object belongs to via drag and drop. But if you select multiple objects, drag and drop does not work any more.

I'd like to change the group of multiple objects via drag and drop. Is this already possible? Or is someone already working on it?

**Comment by mstarke** [comment] 2018-10-05 12:00
Feature is on the roadmap. Duplicate of #515

**Closed by mstarke** 2018-10-05 12:01 UTC
