### ISSUE TITLE
MacPass doesn't lock database properly on reboot

### ISSUE THREAD

**Issue by ilmari-abaenglish** [MacPass/MacPass#824] opened 2018-09-10 07:52 UTC
**Describe the bug**
When you restart or shutdown/start your computer MacPass is momentarily unlocked after restart. 

**To Reproduce**
Steps to reproduce the behaviour: 
1. Open MacPass and leave the database unlocked
2. "Shut down..." your Mac with the option "Reopen windows when logging back in"
3. Start your computer again, and notice how MacPass continues to be unlocked with the database visible after reboot for a second or so before it locks automatically.

**Expected behaviour**
MacPass detects the shutdown and locks the database before shutdown. It doesn't seem very secure that it's unlocked after reboot.

**Desktop (please complete the following information):**
 - macOS: 10.13.6
 - Version: 0.7.3

**Comment by mstarke** [comment] 2018-09-14 12:08
Duplicate of #344

**Closed** 2018-09-14 12:09 UTC
