### ISSUE TITLE
cant access file after wrongly set the keyfile

### ISSUE THREAD

**Issue by agsp-git** [MacPass/MacPass#1157] opened 2021-03-14 09:37 UTC
**Describe the bug**
I want to update the .kdbx master password but accidentally select that database as the 'keyfile', now I can't open it

**To Reproduce**
1. Go to 'File' the 'Change Master Password'
2. Input new password and reconfirm 
3. Keyfile: select the current .kdbx file (I think this is what's wrong)
4. Click 'Change Password'
5. Click 'File' in the main menu, then click 'Lock'
6. Try to reopen the file using the new password

 - macOS: Mojave
 - Version 10.14.6

How to recover it?
Thanks

**Comment by mstarke** [comment] 2021-03-14 11:12
Since this issue did rise up multiple times, a check to prevent usage of .kdbx files was added but it's not released yet. Since the file changes on every save you may be able to unlock it, if you get access to a backup right before you did save the file. This is the only way to recover the data in the saved file. Alternatively you have to get back to a backup file altogether. I'm sorry for not having rolled out this change any sooner to prevent this kind of miss-use.

**Comment by agsp-git** [comment] 2021-03-14 13:08
thanks for the info. hope it will be updated soon.
is there any backup plugin similar to this: https://keepass.info/plugins.html#dbbackup
for macpass?

**Comment by mstarke** [comment] 2021-03-14 13:25
Nope since I did think most macOS users use time machine for backups. But it might be a good idea for additional security to save scheduled backups…

**Comment by georgesnow** [comment] 2021-03-14 14:36
Interesting I was just thinking about regular backups ie specific time or before each save...

@mstarke Is this a feature that you would want in the main app or do you see it as a plug-in? I ask cause I was already looking at how to do this. Just curious which path might be a better way to go.

**Comment by mstarke** [comment] 2021-03-21 11:07
A backup feature seems rather elementary so this would suggest adding it as a core functionality. On the other hand implementing this as plug-in will lead to a extended plugin API which might open up the path for more customizations.

**Comment by mstarke** [comment] 2021-03-22 14:48
I'm closing this since the issue is resolved (sadly rather unsatisfactory bot nonetheless)

**Closed by mstarke** 2021-03-22 14:48 UTC
