### ISSUE TITLE
Selected entry should be in "read only"

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#791] opened 2018-05-16 18:50 UTC
The selected entry is always "editable" in the side panel, but most of the time, you don't need to edit entries.

This is particularly strange when you use the search, I'm worried to use the keyboard and shortcut have I have an entry in "edit mode". The worst is when you are in the search result views and create a new entry because you stay in the selected entry instead of switching to the new one (I guess this part is a bug).

I think it should be more like the Contact.app on MacOS. You can select an entry, copy information... but when you want to edit you actively have to click the "edit" button. And if you create a new entry is directly in the edit mode.

**Comment by mstarke** [comment] 2018-05-17 09:19
An Edit mode is something that was planned in the process of adding history support but dropped since I wanted to remove an additional click. The culprit is that you can accidentally edit a lot of stuff so this is rightfully considered harmful and I might give this another try.

**Comment by gagarine** [comment] 2018-05-28 13:35
The others UX problem is that you are forced to read all the field even the empty one. A reading mode can display only the field that have content. I also imagine that field will display a "copy" label on over that you can click on it to copies the field value.

For me this is the last needed feature before I can give this software to my mum ;).

**Comment by mstarke** [comment] 2018-06-27 16:14
I did some tests to use NSStackViews and hide all empty fields that seem promising. The creation of an edit mode will have consequences on the currently system of creating history entries but this shouldn't be a problem. The biggest change however is another model for editing. The edit/cancel setup will require a decoupling from the UI to the underlying model until the edit is finished. This will remove the need to use all those custom binding controllers but it requires some rather drastic changes to the whole system.

**Comment by mstarke** [comment] 2022-02-21 14:35
I'm closing this since it's a duplicate of #47

**Closed by mstarke** 2022-02-21 14:35 UTC
Labels: Duplicate
