### ISSUE TITLE
Will not let me select .key file

### ISSUE THREAD

**Issue by dcosseboom** [MacPass/MacPass#1005] opened 2019-11-15 17:09 UTC
After updating to version 0.7.10, when I click to choose a keyfile to open a kdbx file the file browser will not let me select open only cancel.  I can no longer open any of my kdbx files.

**Comment by mstarke** [comment] 2019-11-15 19:41
What os are you running? Are you able to open other files with a different extension?

**Comment by mstarke** [comment] 2019-11-18 09:05
@dcosseboom did you solve the problem?

**Comment by dcosseboom** [comment] 2019-11-18 14:47
I am on Mac OS 10.15.  

to clarify.  I am attempting to open a kdbx file (not as a keyfile).  I enter the password, click choose for the keyfile, it opens a file browser, I select my XXXX.key file and it will not let me choose it or any other file.  My only option is to cancel.

**Comment by mstarke** [comment] 2019-11-19 10:45
I can reproduce the issue with 10.15. The problem is the Dialog does not work correctly. If you hit the cancel button, the OK button seems to get the click. I did get it to work when using pressing "Enter" to confirm. This might get fixed when I build with the 10.15 SDK.

**Comment by wotok** [comment] 2019-11-19 16:55
I'm on 10.15.1 and I'm have the same issue. The enter key is not working like you suggested. Also, every time I hit cancel on the dialog, it just cancels the dialog.

**Comment by ryanw3b3r** [comment] 2019-11-21 13:42
Can confirm this on macOS 10.15.1. Really annoying! I can't open my kdbx file, so have to look for another app. Cancel button does absolutely nothing, OK is disabled. I can only click on various files to select them, cannot deselect them. I can press Esc to close dialog.

**Comment by ryanw3b3r** [comment] 2019-11-21 13:49
Ok, got it working. Workaround: open "Select key file" dialog, select key file [Open button will be disabled], right click few times on the key file [Open button should become active], start moving mouse within Open button a click like a maniac. Works for me!

**Comment by mstarke** [comment] 2019-11-22 21:14
I've changed the NSOpenPanel call to be non-blocking so this might fix this issue. The continous release has the supposed fix, if anyone can try this I would be very greatful. I'm going to test this ASAP on a 10.15.1 system.

**Comment by georgesnow** [comment] 2019-11-22 21:52
What are specifics that need to be tested against? (Version of MP and macos, etc...) I can probably test it tonight or tomorrow once I know the specifics

**Comment by mstarke** [comment] 2019-11-23 08:04
As stated in the issue, the key file selection dialog seems to be broken under Catalina.

**Comment by georgesnow** [comment] 2019-11-23 11:53
I just downloaded and tested fresh install of 0.7.10, macOS 10.15.1, created a new database and key file to test with. I couldn't reproduce this issue.

**Comment by mstarke** [comment] 2019-11-25 13:18
I did test the new way on 10.15.1 and it seems to have fixed the issue. Fix will be included in 0.7.11

**Closed by mstarke** 2019-11-25 13:18 UTC
Labels: Bug, macOS 10.15
