### ISSUE TITLE
table view - allow to display passwords?

### ISSUE THREAD

**Issue by rickcr** [MacPass/MacPass#347] opened 2015-06-12 13:48 UTC
First off, great app. Perfect for my parents who just want a way to view their passwords to some accounts. 
Is there any chance though you could allow viewing the passwords in the grid view?  This would be handy as, since they don't have that many passwords, they could quickly view them without having to first click on the row.

Sorry if this is an open ticket or an option somewhere. I searched through some issues and didn't find it.

**Comment by mstarke** [comment] 2015-06-22 08:33
Considered. It's just another dip-switch in the settings ;)

**Comment by drewdroid** [comment] 2015-09-14 02:54
I second this request. Pleeeeeease.. with a cherry on top.  I would like to easily see my passwords in the table form without going to each individually. This would also let me easily see *overused* passwords. Loved this feature on Keepass but MacPass doesn't have it :(. I actually went into the issues section looking for it. 

Love the software by the way, had to search high and low for a keepass client for mac that I liked.

**Comment by chrismjspencer** [comment] 2016-12-16 01:32
Another vote for this. MacPass is incredible, I've spent so many hours looking for a keepass replacement now I've switched to a Mac. But please can we have a feature to show the passwords in free text in tabular format?

**Comment by mstarke** [comment] 2021-02-08 20:18
Duplicate of #347

**Comment by OVER10** [comment] 2021-03-13 11:03
Any chance on this feature being added?

**Comment by mstarke** [comment] 2021-03-13 11:06
Quite likely. It‘s more or less done already but needs minor tweaks. It should get published with 0.8.

**Closed** 2021-11-10 19:38 UTC
Labels: Enhancement
