### ISSUE TITLE
First use of autotype writes content of clipboard

### ISSUE THREAD

**Issue by fjl** [MacPass/MacPass#395] opened 2015-12-08 18:51 UTC
(using commit 204f41356036975fa9079aad95bbe029469ded30)

The very first use of autotype with a global keyboard shortcut fails
reliably, producing the content of the clipboard instead of the credentials.

Steps to reproduce:
- Add a new entry with password `foobarfoobarfoobar`
- Open gist.github.com
- Add a window association for title "Create a new gist" to the entry
- Set autotype sequence to "{PASSWORD}{ENTER}"
- Save the DB, close MacPass
- Open MacPass, unlock the DB
- Copy `204f41356036975fa9079aad95bbe029469ded30`
- Switch to browser, hit the global autotype shortcut.
  The gist now contains `204f41356036975fa9079aad95bbe029469ded30`
- Hit the shortcut again, this time MacPass types `foobarfoobarfoobar` as expected.

**Comment by fjl** [comment] 2015-12-08 18:56
While creating the repro steps that the 'garbage' being typed is actually the content of the clipboard.

**Comment by mstarke** [comment] 2015-12-13 11:04
This seems to be a timing issue - which did occur in Yosemite too.

**Comment by gagarine** [comment] 2018-11-18 12:53
I do have the same bug with Mojave and macpass 0.7.3 (can wait for a new stable release, so many bugs have been fixed).

Note that I'm using https://clipy-app.com . Don't know but perhaps it makes this bug append more often. Because I'm surprised so few peoples reported it. It seems to append regularly (1-2 times a day I would say).

It's a bit of a problem because I can potentially send sensitive information to the website I'm trying to log it. I never copy in my clipboard ultra-sensitive information, as clipboard is shared between applications. But I may copy an email or source code that I don't want to be public.

To mitigate the risque with this bug I wanted to change the autotype sequence for all my entries by removing the "enter", but didn't find out how to do it.

**Comment by mstarke** [comment] 2018-11-20 21:38
The current version is using single key press events instead of copy paste for nearly all typing so this error should be fixed. I can confirm that is is more or less reproducibly after the first use of Autotype in MacPass.

**Comment by mstarke** [comment] 2021-01-18 13:56
This should be fixed with 0.7.4 and the move to key press events instead of copy/paste

**Closed by mstarke** 2021-01-18 13:56 UTC
Labels: Bug
