### ISSUE TITLE
[Feature Request] Drag and Drop of Multiple Entries

### ISSUE THREAD

**Issue by ghost** [MacPass/MacPass#515] opened 2016-11-26 12:50 UTC
I recently tried to select hundreds of entries and wanted to move them in a new group. Couldn't figure out how to do it.

Selecting and moving multiple entries at once would be helpful.

**Comment by mstarke** [comment] 2017-01-24 11:05
Multiselect is working in master is there but drag and drop support for it is still missing.

**Comment by tflo** [comment] 2017-10-11 13:52
Yep, support for dragging multiple items to a different folder would be great!

**Comment by magebarf** [comment] 2017-12-20 23:12
Joining the choir here!
Will possibly have a look at it myself if I find the time.

**Comment by NikolausDemmel** [comment] 2018-01-06 13:53
+1 for drag-and-drop with multiple items. In particular in combination with #721 this can make things tedious.

**Comment by mstarke** [comment] 2018-10-05 11:59
Duplicate of #285

**Comment by mstarke** [comment] 2019-03-19 09:55
Released in 0.7.4

**Closed by mstarke** 2019-03-19 09:55 UTC
Labels: Enhancement
