### ISSUE TITLE
Search Everywhere field doesn't work

### ISSUE THREAD

**Issue by Francescoliverio** [MacPass/MacPass#1159] opened 2021-03-22 10:16 UTC
**Describe the bug**
At the beginning when you open MacPass the filter search work properly. After some times it doesn't work and then I should close the MacPass App and reopen again if I wanna search something.

**Comment by mstarke** [comment] 2021-03-22 14:45
This is related to the know issues with the toolbar under Big Sur. Duplicate of #1113

**Closed by mstarke** 2021-03-22 14:45 UTC
