### ISSUE TITLE
Autotype with Firefox not working any more

### ISSUE THREAD

**Issue by walkabout17** [MacPass/MacPass#734] opened 2018-01-31 22:01 UTC
MacPass Version 0.7.3 (17830)
Firefox 58.0.1 (64-Bit)
Autotype with command shift U and command ctrl A copies the contents of clipboard to the input fields. Please help!
Thank you!

**Comment by mstarke** [comment] 2018-02-02 10:06
Your title stated "not working anymore" since when did this happen? Does it correlate with a Firefox update or a MacPass update?

**Comment by walkabout17** [comment] 2018-02-02 11:16
I made a few other tests. The exact problem is, that with autotype the username is shortened and consisting of stochastically (at least it looks like that) extracted or mixed characters. The password is filled out right with autotype!!!

Two examples:
username: kernharald -> autotype: ehrad, next try: 480216e40h2ra1d
username: 4802164021 -> autotypes: 81021, next try: 8810121021

For me, main correlation is, that I installed MacPass 0.7.3. after clean install of high sierra (10.13.3 (17D47)). After clean install I installed firefox (same version as before with sierra). In sierra I used the previous version of MacPass and everything worked well.

Next step for me would be: export database, delete the old one db, make a new one and import the contents.

Thank you, Danke
Harald

**Comment by mstarke** [comment] 2018-02-02 12:00
The database should not be the cause of the issue. Do you use global auto-type via a hot-key or do you invoke auto-type from MacPass?

**Comment by mstarke** [comment] 2018-02-02 12:00
And I'm still on 10.12 so this might be a 10.13 related issue.

**Comment by walkabout17** [comment] 2018-02-02 12:23
1. mark the entry in the open database
2. shift cmd U to open the adress (is opened with firefox, my standard browser)
3. go back to MacPass (mouse click on the window frame)
4. ctrl cmd A to execute autotype

**Comment by walkabout17** [comment] 2018-02-02 17:18
I guess it's not an issue with high sierra, because with safari autotype is working fine!

**Comment by mstarke** [comment] 2018-02-03 11:10
Thank you for the clarification. The clipboard is supplied by a daemon in macOS and sometimes the key events to paste arrive before the clipboard is filled with the actual content. This might be an edge case for Firefox and it's UI. I'll have to replicate this in my end and try to come up with a fix. As a side note: the Autotype system needs a rewrite to move away from clipboard usage to simulate more key presses which might fix such problems as well but this is still far out.

**Comment by walkabout17** [comment] 2018-02-03 16:11
Thank you for the explanation and fast reaction!

**Comment by mstarke** [comment] 2018-03-16 20:47
Strange since there aren't any changes regarding to this issue.

**Comment by mstarke** [comment] 2018-03-16 20:49
As an aside: I noticed the behaviour of truncated usernames in Safari under macOS 10.12 to but only on a certain website.

**Comment by alexbde** [comment] 2018-03-17 10:16
Okay. Maybe it's only I haven't notice it since then ;)

**Comment by walkabout17** [comment] 2018-04-02 13:49
Seems like it's woking again:
MacPass 0.7.3 (17830)
macOS 10.13.4 (17E199)
Firefox 59.0.2 (64-Bit)
At the moment I'm not able to reproduce the issue!

**Comment by mstarke** [comment] 2018-09-16 17:55
Closing since it seems to be fixed or not reproduceable anymore. Pleas re-open or re-submitt if the issue raises again.

**Closed by mstarke** 2018-09-16 17:55 UTC
