### ISSUE TITLE
Opening KDBX corrupts attachments and removes entries

### ISSUE THREAD

**Issue by josmad** [MacPass/MacPass#819] opened 2018-08-15 13:47 UTC
**Describe the bug**
When an existing KDBX DB, containing entries with attachments, is opened in MacPass
some of the entries are corrupted/removed.
The DB file size was reduced by ~12% after having been opened in MacPass.

**To Reproduce**
1. Using KeePass, Create, populate, and save a KDBX DB with entries containing attachments.
2. Transfer KDBX DB to a Mac and decrypt the DB with MacPass
3. See that decrypting the DB with MacPass has changed the size
4. Transfer the KDBX DB back to the Windows machine with KeePass.
Decrypt the DB and see that some attachments have been corrupted

**Expected behavior**
MacPass does not modify the DB on its own.
MacPass does not corrupt entries. 

**Desktop (please complete the following information):**
 - macOS: 10.13.6
 - Version 0.7.3

**Additional context**
- Keepass: 2.39.1
KDBX is synced across machines using DropBox.

**Comment by mstarke** [comment] 2018-08-15 13:51
There is a know issue with attachments with the same binary data being not properly handled by MacPass but those should not result in actual data loss or corruption (see #788).

File size changes do occur due to differences in compression algorithms and should never yield data loss.

Can you try to create a minimal example for attachment data loss/corruption?

**Comment by mstarke** [comment] 2018-08-22 20:53
Any chance you find the time for a minimal example?

**Comment by mstarke** [comment] 2018-08-25 07:00
@josmad If you could give more context would be awesome. Since you describe a serious data-loss which should be eliminated ASAP. I cannot reproduce this setup so your help is vital.

**Comment by josmad** [comment] 2018-09-05 08:18
Sorry completely forgot about this. I can try creating an example today/tomorrow.
Will update.

**Comment by mstarke** [comment] 2018-11-12 11:32
I'm closing this for now until the issue comes up again.

**Closed by mstarke** 2018-11-12 11:32 UTC
Labels: Bug
