### ISSUE TITLE
Open database by default in read-only mode

### ISSUE THREAD

**Issue by eedrah** [MacPass/MacPass#867] opened 2019-01-03 02:54 UTC
First, thanks for a great app!

**Is your feature request related to a problem? Please describe.**
I find that I open the database to read the passwords much more than I edit them. It seems very easy to edit passwords (which is a great thing) but most of the time I'm not looking for this behavior - I mistakenly edit passwords/fields when only trying to look at them.

**Describe the solution you'd like**
Having the database explicitly in read-only mode by default, and then having a dialogue box asking you if you want to edit it (or just informing you need to go elsewhere to turn off read-only) would feel a lot safer. Especially given the auto-save functionality which can hide your changes/erasures and save/delete this permanently back to your master database.

**Describe alternatives you've considered**
#718 has an alternative - putting the functionality not on the entire database, but on the current entry individually.

**Comment by oehm-smith** [comment] 2019-01-03 03:45
I agree.  I all too often have to be vigilant when working with MacPass.  I haven't yet changed / deleted something inadvertently.  I think / hope :)

**Comment by neeklamy** [comment] 2019-01-03 12:15
Or how about an explicit edit item mode? 1Password requires you to hit the edit button before any changes can be made. And just in case you still manage to hose a password item, they automatically keep encrypted backups of the database.

![1password-edit-button](https://user-images.githubusercontent.com/155358/50637142-b3366e80-0f50-11e9-8817-5b6f836462bf.png)

**Comment by mstarke** [comment] 2019-01-03 17:43
Solution should be an edit mode - Duplicate of #47

**Closed by mstarke** 2019-01-03 17:43 UTC
