### ISSUE TITLE
[Feature Request] Copy Shortcuts and Minimize on Copy

### ISSUE THREAD

**Issue by robbpriestley** [MacPass/MacPass#648] opened 2017-09-13 22:25 UTC
KeePassX and KeePassXC have very handy shortcuts:

CMD-B: Copy username to clipboard
CMD-C: Copy password to clipboard

As well there is an awesome feature with KeePassX and XC that when you use one of the copy commands above, the application is automatically minimized so you can paste into the other application very quickly and effectively.

If these features come to MacPass, I'll become a user. I already like the MacPass look and feel. Just needs these functional improvements IMHO.

**Comment by DominusExult** [comment] 2017-09-14 06:43
1. You can reassign shortcuts in the OS X shortcuts/keyboard manager in the OS X settings app
2. With today’s big screens *I* would find it cumbersome when copying one and then needing the other one to have to "open" MacPass again. But that’s just my opinion ;)

**Comment by mstarke** [comment] 2017-09-14 07:06
Additionally MacPass allows you to copy usernames, passwords or urls by double clicking on the column of the entry. Another solution for you might be to use Autotype. This way MacPass puts the app back in front, that was front-most before you switched to MacPass.

**Comment by robbpriestley** [comment] 2017-09-15 02:02
As far as I can tell, re-assigning shortcuts only works with main menu items. But when I was looking around trying to figure this out, I noticed you *do* have shortcuts to copy usernames and passwords. But they're hidden in a context menu. I guess I can live with the 3-key shortcuts but I'd really prefer 2-key ones for efficiency. And why not put them in the Edit menu?

**Comment by mstarke** [comment] 2017-09-15 04:08
It doesn't matter whether the entires reside in the main menus or inside a context menu. You can set custom shortcuts for all of them. What might happen is, that you will not see them correctly displayed but they should work.

**Comment by robbpriestley** [comment] 2017-09-15 13:34
I appreciate the time you're taking to communicate about this, and I am going to give MacPass a try, but FYI the Copy Username and Copy Password context menu items won't remap to new keyboard shortcuts, whereas main menu items will.

**Comment by mstarke** [comment] 2017-09-15 13:45
I just tested it with - alas with the current continuous build - and it does work. What is indeed broken is the diplay.

Here's my system settings:
![screen shot 2017-09-15 at 15 41 28](https://user-images.githubusercontent.com/58428/30485093-a6577aa0-9a2c-11e7-9726-1d05ab544100.png)
And here's the context menu, that gets rendered:
![screen shot 2017-09-15 at 15 40 57](https://user-images.githubusercontent.com/58428/30485115-b68a04b0-9a2c-11e7-9138-eb0671c4b067.png)

Pressing ```cmd + C``` dose however copy the password and ```cmd + B``` copies the username

**Comment by mstarke** [comment] 2017-09-15 13:51
I just found a nice bug. The Context-Menu does render Copy Username wrong, the Action Button Menu however does correctly render both updated keyboard shortcuts.

**Comment by bbyk** [comment] 2018-03-15 00:39
I noticed that I had to restart MacPass for the remapping in `System Preferences -> Keyboard -> Shortcuts` to go into effect. That's probably by design.

**Comment by mstarke** [comment] 2018-03-15 16:05
@bbyk true. Restarts are needed. Sometimes even multiple ones to make the changes take effect.

@robbpriestley Regarding minimizing after a copy that is something I can add as well. This should be included in the workflow settings as I personally would hate this behaviour.

**Comment by websocket98765** [comment] 2019-12-25 03:13
> I just tested it with - alas with the current continuous build - and it does work. What is indeed broken is the diplay.
> 
> Here's my system settings:
> ![screen shot 2017-09-15 at 15 41 28](https://user-images.githubusercontent.com/58428/30485093-a6577aa0-9a2c-11e7-9726-1d05ab544100.png)
> And here's the context menu, that gets rendered:
> ![screen shot 2017-09-15 at 15 40 57](https://user-images.githubusercontent.com/58428/30485115-b68a04b0-9a2c-11e7-9138-eb0671c4b067.png)
> 
> Pressing `cmd + C` dose however copy the password and `cmd + B` copies the username

In case helpful, confirming that I still experience this issue in current MacPass version 0.7.10 and Mac 10.15

**Comment by mstarke** [comment] 2020-02-12 09:24
The shortcuts-debate is an ongoing thing so I'm closing this since a duplicate issue the hide after copy option was added in 0.7.10 (see #906)

**Closed by mstarke** 2020-02-12 09:24 UTC

**Comment by websocket98765** [comment] 2020-02-29 16:58
Remember to track this issue somewhere then, where shortcut menu incorrectly shows currently assigned shortcut. This still exists:
![ctrl+c issue](https://user-images.githubusercontent.com/41795874/75611674-7e05bc00-5b14-11ea-90e5-d96618d74098.png)
(This is when using MacOS system settings to change keyboard shortcuts for Copy Username to Ctrl+B and Copy Password to Ctrl+C.)
