### ISSUE TITLE
Load Database via http or FTP(e)s

### ISSUE THREAD

**Issue by lastsamurai26** [MacPass/MacPass#973] opened 2019-09-08 00:20 UTC
**Is your feature request related to a problem? Please describe.**
I have my database Local and Via FTP on the NAS of a known one. I am annoyed every time I have to copy this database on the server via FTP program. It would be great if I could open a database from the internet as a URL and save it with the appropriate access data. 

like in KeePass(Windows)

**Describe the solution you'd like**
A function to open a database via URL or ftp

**Comment by mstarke** [comment] 2019-09-09 10:27
Duplicate of #919. Until there's better support in the core frameworks I'm hesitant to roll my own sync engine.

**Closed by mstarke** 2019-09-09 10:27 UTC
