### ISSUE TITLE
Settings not saved after reopen

### ISSUE THREAD

**Issue by furashcka** [MacPass/MacPass#1009] opened 2019-11-23 11:23 UTC
Hello, when i select "Double-click URL: Copies URL" after close and reopen MacPass a have "Double-click URL: Opens URL", and i always select "Double-click URL: Copies URL" when open, can you fix please? :)

**Comment by mstarke** [comment] 2019-11-23 11:36
Duplicate of #989 Fixed in upcoming 0.7.11

**Closed by mstarke** 2019-11-23 11:36 UTC

**Comment by furashcka** [comment] 2019-11-23 17:38
thanks :)
