### ISSUE TITLE
Support for multiline custom fields

### ISSUE THREAD

**Issue by ain** [MacPass/MacPass#306] opened 2015-01-20 16:17 UTC
KeePassX has a field for SSH Config which is essentially a multiline field, but comes over to MacPass into a single-line input. 

Whilst the content in it is correct, it's deceiving and I'd propose to run a simple detector on custom fields incoming from other clients such as KeePassX and then, according to the findings, inject either a single-line or multiline input. Shouldn't be a big change, I hope?

**Comment by mstarke** [comment] 2015-01-22 16:07
I guess you mean that all custom fields in Keepass(X) are shown as mulit line inputs, not so in MacPass.

This was a simple UI Decision in the past and I have been pondering about the issue as well. Goes so far as to add lines when you break them in the input field. I think there needs to be some more time spend on how the UI for custom fields works.

And since it shouldn't be such a big change, I'm waiting for you pull request :P. Sorry, couldn't resist :)

**Comment by ain** [comment] 2015-01-22 21:11
Thanks. Would love to, but I'm not really a Obj-C guy. It'd take me ages to make this simple change and end up in a PR that you'd then most likely rewrite :)

**Comment by mstarke** [comment] 2018-09-14 12:04
Duplicate of #27.

**Closed by mstarke** 2018-09-14 12:04 UTC
Labels: Enhancement, Keepass Feature
