### ISSUE TITLE
New generator based on english words

### ISSUE THREAD

**Issue by bkolada** [MacPass/MacPass#518] opened 2016-11-29 21:47 UTC
Hey, 
it could be nice to have generator of passwords from list of english words. To have something like:
BananaJob12tree it could be easier to write and read.

**Comment by 9point6** [comment] 2016-11-30 10:12
Or a step further - plugin support for password generation algorithms!

**Comment by bkolada** [comment] 2016-11-30 10:17
Actually it could be better, my idea was a bit narrow.

**Comment by woyczek** [comment] 2017-02-06 14:31
Such a plugin exists in KP for windows. Is it possible to reuse the code, or are the plugin framework totally differents ?

**Comment by mstarke** [comment] 2017-02-06 14:40
KeePass code is incompatible with MacPass. It requires a custom MacPass plugin.

**Comment by cipnt** [comment] 2017-05-16 18:48
Personally I prefer mnemonic passwords, but agree it would be nice to have multiple options (random characters, random dictionary words, mnemonic,, etc)

**Comment by michaelblyons** [comment] 2017-09-05 20:49
Duplicate of #458?

**Comment by qjinni** [comment] 2017-09-05 21:18
@michaelblyons looks like it is

**Comment by mstarke** [comment] 2021-01-21 15:05
Yup. Duplicate of #458

**Closed by mstarke** 2021-01-21 15:05 UTC
Labels: Plugin
