### ISSUE TITLE
Always select the new entry when created

### ISSUE THREAD

**Issue by gagarine** [MacPass/MacPass#801] opened 2018-06-04 18:49 UTC
If you have a entry selected (in blue), when you create a new entry you stay on the selected entry. This is not cool.

**To Reproduce**
1. Select an entry
2. Click on 'new entry'
3. You stay on the selected entry :(

This is particularly problematic if you have search, has the new entry is not even in the list. Also depending of your sort order, the new entry can be at the end of the list or even in a "random" place.

**Comment by mstarke** [comment] 2018-06-06 20:56
There seem to be a lot of UI bugs related to 10.13. The behaviour under 10.12 is correct - that is, newly created entries get selected. I'm in the process of moving my development setup to 10.13 so those issues will get addressed as soon as I'm on 10.13.

**Comment by mstarke** [comment] 2018-08-06 08:14
I cannot reproduce this bug. If I add an entry, the entry gets selected and the focus is set to the title field. System is 10.13.6. MacPass continuous

**Comment by gagarine** [comment] 2018-08-10 17:14
I'm on 0.7.3. I will check it again. But perhaps I can try on a new release if one is planned soon.

**Comment by mstarke** [comment] 2018-09-14 12:01
Closing since it's not reproduceable on my end. Please re-open when it occurs again.

**Closed by mstarke** 2018-09-14 12:01 UTC
Labels: Bug, macOS 10.13
