### ISSUE TITLE
Autotype for User and Password only

### ISSUE THREAD

**Issue by 23tux** [MacPass/MacPass#1039] opened 2020-02-12 08:45 UTC
**Is your feature request related to a problem? Please describe.**
Some sites split the login panel in different sites. First you have to enter your email then click on next and then you enter the password. Other sites (Google for example) display a password field when they want to verify it's you.

In both cases you can't use auto type and you have to go into MacPass, search the site and copy the password. The whole process feels tedious.

**Describe the solution you'd like**
A special shortcut that only auto types username or password would be perfect.

**Comment by mstarke** [comment] 2020-02-12 09:30
This has been requested multiple times. The current solution for this is to use  ```{PICKFIELD}{ENTER}``` as a custom Autotype sequence. This will show MacPass and a dialog box to select what item to choose. This is a global solution but a direct selection for password and/or username makes the whole workflow faster. This however then is a very rigid solution and it might be useful to add an option between the generic ```{PICKFIELD}``` solution and direct hard-coded custom sequences.

My current ideas:

1. Implement something like KeePass has and allow for "Autotype with custom sequence…" shortcut that will present a dialog with some shortcuts
2. Extend the above by allowing to bind keyboard shortcuts to the custom sequences (e.g. use a slot based system)
3. Add special shortcuts for common Autotype sequecnes (e.g. ```{PASSWORD}{ENTER}``` or ```{USERNAME}{ENTER}```

My current favourite is **2.** but this requires some time to get done.

As I was investigating the old issues I found this one #974 which seem like you had the problem before. Is using ```{PICKFIELD}{ENTER}``` not working for you anymore?

**Comment by mstarke** [comment] 2020-02-12 09:31
duplicate of #974

**Comment by georgesnow** [comment] 2020-02-12 11:17
I agree with tedious thing. One thing I have been trying out in my plugin is using that same AppleScript for AutotypeURL. It sets the search context in MP when using the hot key in MacPassRevealer. There is a branch called SafariContext if that interests you. 

Instead of using global auto type you trigger hotkey while on Safari to reveal MP and the search context is set to whatever the url is. Then you can copy username (turn on hide on copy) and then trigger the hotkey and do the same for the password. 

I have used for the above situation since Amazon moved to same style speed bump login page setup. That branch version is not amazing it is work in progress and needs some improvement. You can get an idea from my commit notes issues and workflow paths that need improvement.


Also It would be nice to have a {COPY} action. But this would require keepass Upstream to support it. It adds some benefits all around. That’s long term option.

**Comment by georgesnow** [comment] 2020-02-12 11:20
I forgot one other piece on other apps it matches and sets the search context based on the app name of the front most app.

**Comment by 23tux** [comment] 2020-02-21 07:38
@mstarke my main problem with `{PICKFIELD}{ENTER}` is that I don't see which account I'm using any more (see screenshot)

![pickfield autotype pop up](https://i.imgur.com/7cqj0SI.png)

I have multiple accounts on Google, and when I use pickfield for every one of them, I don't see which account I'm using. Furthermore, I would have to change a lot of accounts to use pickfield, so a global shortcut for "Auto Type / Copy Password" and "Auto Type / Copy Username" would be helpful.

**Comment by xdhmoore** [comment] 2020-10-07 00:45
For what it's worth, a solution that could be configured similarly to the 2 global shortcuts of KeePass would be a bonus for me. I use both apps frequently, and I often find myself entering the shortcut for the wrong app or forgetting which is which.

**Comment by 23tux** [comment] 2020-10-07 04:18
Another annoying use case is the trend of sites, to split username and password. E.g. Evernote or Google (and many other sites).

You can't just autotype user + password:
- Fill out username
- Wait for interface to respond to show the password field
- Now, when you have autotype for user AND password and you try to select the username again, it hides the password field 🤦‍♂️ 

Here is a GIF from evernote demonstrating this:

![Oct-07-2020 06-14-58](https://user-images.githubusercontent.com/38003/95286887-dd733980-0864-11eb-89de-dcc57a059868.gif)

A dedicated shortcut for typing user OR password would solve this.

**Comment by xdhmoore** [comment] 2020-10-07 20:33
@23tux I've had some moderate success using things like the following for cases like that.

```
{CLEARFIELD}{USERNAME}{DELAY 500}{ENTER}{DELAY 500}{PASSWORD}{ENTER}
```

Of course, it's kindof a pain to try to configure every variation of every site this way...

**Comment by 23tux** [comment] 2020-10-09 08:01
@xdhmoore I think it's cool that you got it working, but indeed that seems pretty brittle.

Futhermore, some site like Stripe require you to enter your password from time to time for specific actions. In this case you only have one input field and the auto typing sequence becomes useless.

So I still think having a global shortcut for only auto typing user OR password would be very useful.

I also had a look into the AppleScript options to do the shortcut myself, but it seems that MacPass doesn't provide an interface for that. From a security view, this makes sense, but from a usability view it would be handy to have some way to achieve a custom workflow.

**Comment by mstarke** [comment] 2020-10-12 12:06
@23tux AppleScript support is something that I always wanted to add but never came to it. Maybe someone can contribute it, since I also have no experience with adding support for AppleScript to an application.

I think I will try to implement a first solution that might lead to solution 2 in https://github.com/MacPass/MacPass/issues/1039#issuecomment-585114041

> 2. Implement something like KeePass has and allow for "Autotype with custom sequence…" shortcut that will present a dialog with some shortcuts

**Closed** 2021-01-28 13:01 UTC
Labels: Duplicate

**Comment by ezamelczyk** [comment] 2024-01-04 19:13
I'm sorry but this is so dumb. I have to configure this for every field I have? Why not just make a global option to autofill just password or username or even better the otp code.
