### ISSUE TITLE
Dark Mode - Notification Icons Cannot be Seen

### ISSUE THREAD

**Issue by robbpriestley** [MacPass/MacPass#1007] opened 2019-11-18 17:38 UTC
**To Reproduce**
Using dark mode, select an entry, then select Item --> Copy Password

**Expected behavior**
The icon in the notification message is visible

**Actual behavior**
The icon in the notification message is black-on-black and cannot be seen

**Screenshots**
![image](https://user-images.githubusercontent.com/16694050/69075835-0b4e5600-09e7-11ea-9098-c43d06d4f602.png)

**Desktop (please complete the following information):**
 - macOS: 10.15

**NOTE**
This problem does not just affect the copy password notification message, it affects all notification messages involving an icon. Copy password is described as an example.

**Comment by georgesnow** [comment] 2019-11-18 19:34
#999 addresses so I linking it

**Comment by mstarke** [comment] 2019-11-22 21:12
Fixed with #999. Duplicate of #982.

**Closed by mstarke** 2019-11-22 21:12 UTC
