### ISSUE TITLE
You Dont Have Permission to Save the File

### ISSUE THREAD

**Issue by marinatin** [MacPass/MacPass#1192] opened 2021-11-23 19:51 UTC
Upon updating to MacOS 12.0.1, I got the following and cant resolve.

Error 1

![image](https://user-images.githubusercontent.com/94931258/143093904-4ca4aede-8432-4826-82a3-0bded5dbca43.png)

Error 2

![image](https://user-images.githubusercontent.com/94931258/143093855-9ba9f36f-7145-44b9-9b2e-b1b5a226d7ba.png)

**Comment by mstarke** [comment] 2021-11-23 22:29
The first issue can be resolved by unlocking the file. This unlock does not mean the MacPass lock/unlock but rather the Locking in the Finder. You can open the info dialog on the file and uncheck the "Locked" box.

For the second issue I have no clue what the cause might be. Did you check the file permission as stated in the dialog?

**Comment by marinatin** [comment] 2021-11-23 23:02
thanks man. tried unlocking from Finder. Wasn't locked and privileges look correct. See attached

Also seems like the file directory where the macpass file lives got moved upon upgrade OS, but I could have made that up. Dropbox seems suspect. 

Solution was to export xml out of MacPass and create a new group. 

![image](https://user-images.githubusercontent.com/94931258/143141878-cdd82a27-ed06-4439-b1ee-681a16baecff.png)

![image](https://user-images.githubusercontent.com/94931258/143141891-e64aa1d1-3141-430d-9b7e-298c7fa44edc.png)

**Comment by mstarke** [comment] 2021-12-03 18:00
The file being located in the ```.dropbox.cache``` is highly suspicious. You should not have access to those files since Dropbox should manage those files.

**Comment by mstarke** [comment] 2021-12-03 18:00
I'm closing this since the underlying issue is solved.

**Closed by mstarke** 2021-12-03 18:00 UTC

**Comment by marinatin** [comment] 2021-12-03 18:04
Thanks my friend.

**Comment by lsiden** [comment] 2022-03-07 17:00
I just reformatted the USB drives as eXFAT and now MacPass can save to it.
