### ISSUE TITLE
Unknown File Format error (1039) after wiping M1 macbook

### ISSUE THREAD

**Issue by davidkieve** [MacPass/MacPass#1291] opened 2024-02-02 15:19 UTC
Creating a new thread for this. Seen a thread about it from years ago, but maybe this is different.

I had to wipe my M1 macbook after a phishing attempt and now can't get into MacPass despite having backed up the key and passes files. The error says "Unknown File Format" (listed as error 1039 on v8 and 1001 on v7). 

Nothing helps in terms of restarting/reinstalling MacPass.

I copied the following to a flash drive beforehand:

KeyFileKeePass copy.kdbx
KeyFileKeePass.key
Passes

Any ideas how to get back in?

<img width="522" alt="Screenshot 2024-02-02 at 10 14 46 AM" src="https://github.com/MacPass/MacPass/assets/72314900/73726314-6840-4c99-9abe-1c8986d8f4fd">

**Comment by georgesnow** [comment] 2024-02-02 16:51
You’re putting your KeePass database in the “key field”.

the key field show by the file that ends in “.key”

**Comment by davidkieve** [comment] 2024-02-03 03:45
> You’re putting your KeePass database in the “key field”.
> 
> the key field should be the file that ends in “.key”

Thanks - I've tried that too and same result.

<img width="448" alt="Screenshot 2024-02-02 at 10 44 35 PM" src="https://github.com/MacPass/MacPass/assets/72314900/5e36ac54-b7cb-4f5f-9569-afbbed0b8e34">

**Comment by mstarke** [comment] 2024-02-04 10:52
To clarify: you open the KDBX file and set the .key file as key, right? Unknown file format does imply that the database is no Keepass file. Have you tried opening the file with another client e.g. Strongbox? Or KeepassXC?

**Comment by davidkieve** [comment] 2024-02-04 11:56
> To clarify: you open the KDBX file and set the .key file as key, right? Unknown file format does imply that the database is no Keepass file. Have you tried opening the file with another client e.g. Strongbox? Or KeepassXC?

Worked with Strongbox! Thank you so much for your help.

**Comment by mstarke** [comment] 2024-02-04 12:39
Out of curiosity: you did open the KDBX file and set the key file and entered the password just like in MacPass? Did this work before in MacPass? What key file format do you use? (Take a look at the version in the .key file. You can open it with a text editor since it’s just an xml file)

**Comment by davidkieve** [comment] 2024-02-04 14:35
> Out of curiosity: you did open the KDBX file and set the key file and entered the password just like in MacPass? Did this work before in MacPass? What key file format do you use? (Take a look at the version in the .key file. You can open it with a text editor since it’s just an xml file)

I have to retrace my steps to double check. It may have been that I've been trying the old copy of the database (from iCloud - which had an old password) instead of the new one from an external drive. Though I was certain that I tried both with MacPass. Oonce I tried the newer one in Strongbox, it worked.

**Comment by mstarke** [comment] 2024-07-02 09:15
I'm closing this since there's no foll up and the issue is resolved

**Closed by mstarke** 2024-07-02 09:15 UTC
