### ISSUE TITLE
Only showing 3

### ISSUE THREAD

**Issue by amoss1970** [MacPass/MacPass#1266] opened 2023-02-16 17:27 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - macOS: [e.g. 10.12.1]
 - Version [e.g. 0.7.3]

**Additional context**

**Comment by amoss1970** [comment] 2023-02-16 17:28
Macpass is only showing first 3 characters of my password, How do I get to see the whole password

**Comment by mstarke** [comment] 2023-02-24 09:22
Duplicate of #1210. Fixed.

**Closed by mstarke** 2023-02-24 09:22 UTC
