### ISSUE TITLE
Master password with ñ problem.

### ISSUE THREAD

**Issue by elmemis** [MacPass/MacPass#503] opened 2016-09-28 14:17 UTC
If master password with ñ on OS X and keyboard International English don't work.

I need write password in other program and copy/paste on MacPass.

Sorry my bad english.

**Comment by mstarke** [comment] 2016-09-28 15:48
Nice find but this is systematic. NSSecuredTextField will not register composed characters, NSTextField however will. A bad workaround for MacPass is to toggle the visibility of the password and type the ñ and then toggle back and type the rest.

**Comment by mstarke** [comment] 2016-10-14 08:00
I have tried to find a solution to this but the only one that might fix you problem is using a NSTextField instead of an NSSecureText with less security or to reimplement NSSecureTextField on my own to work around this behaviour.

**Comment by valueff** [comment] 2018-09-22 07:01
Thanks for the answer. I'll switch to passwords in Latin)

**Comment by mstarke** [comment] 2018-09-22 07:10
I'm sorry for the inconvenience but this seems to be a mayor issue for some regions. I have no clue how other password tools handle this gracefully. Changing the input to a new one is also hard since it will break old containers that use special characters. 

This is a rather complex problem which. Changing the input system to allow for "normal" text input already would break latin passwords as well. If someone uses the password ```ñotes``` and normally types it by pressing ```~``` and then ```N```to get the combined character ñ the secure input will actually record every key and the password then is ```~notes```.

**Comment by mstarke** [comment] 2019-11-11 10:53
I am closing this since the problem is a Cocoa issue that might never be resolved. Switching to Catalyst or SwiftUI might fix this. A custom password input is something I am not keen on implementing.

**Closed by mstarke** 2019-11-11 10:53 UTC
Labels: Help Wanted!
