### ISSUE TITLE
Saving a kdbx makes it unreadable for KeePassX 2.0.3 (MacOS)

### ISSUE THREAD

**Issue by mfriess2** [MacPass/MacPass#857] opened 2018-12-04 12:51 UTC
MacPass version: 0.7.3
KeePassX (Mac) version: 2.0.3

Saving a database (kdbx) in MacPass and trying to open it with KeePassX brings up the attached error:
![image](https://user-images.githubusercontent.com/11044883/49443042-9bda5900-f7cb-11e8-9f62-ae0c8936ddf5.png)

The error occurs directly after entering the master password!
A keyfile is not used.

This makes it impossible to share a keepass database across operating systems (e.g. KeePassX under Linux).

**Comment by mstarke** [comment] 2018-12-04 12:55
Issue is known and fixed in master/Continuous. Will be published in 0.7.4. ASAP. Sorry for the long delay. Duplicate of #788

**Comment by mfriess2** [comment] 2018-12-04 12:55
Cool, thanks and looking forward to it!

**Closed by mstarke** 2018-12-04 12:55 UTC
