### ISSUE TITLE
Make keyboard shortcuts configurable

### ISSUE THREAD

**Issue by pmhausen** [MacPass/MacPass#835] opened 2018-09-26 20:28 UTC
**Is your feature request related to a problem? Please describe.**
I'd really like to get Cmd-C == "copy password to clipboard" back. Being able to freely map keyboard actions to commands would be great.

**Describe the solution you'd like**
See above.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by mstarke** [comment] 2018-09-27 06:54
You can remap keyboard shortcuts for any macOS application by using the system preferences. Duplicate of #556

**Closed by mstarke** 2018-09-27 06:54 UTC

**Comment by pmhausen** [comment] 2018-09-27 07:04
As far as I know - and the linked Apple support document states the same - this only applies to menu commands. I could not find a menu entry for "copy password to clipboard" in MacPass ...

Kind regards,
Patrick

**Comment by mstarke** [comment] 2018-09-27 07:56
Menu items do not have to be in the Main menu. The "Action" Menu or the Context menu for an entry is also valid.
![screen shot 2018-09-27 at 09 53 57](https://user-images.githubusercontent.com/58428/46131252-7f55f980-c23b-11e8-963e-56473129bfeb.png)

0.7.4 also has a Item menu in the main menu bar to make the functionality more obvious.

**Comment by mstarke** [comment] 2018-09-27 07:59
Just to clarify: There aren't many places where a normal Cocoa application need to do custom keyboard shortcut handling, it mostly boils down to menu items and key equivalents. MacPass only does this for the Global Autotype Hotkey for obvious reasons.

**Comment by mstarke** [comment] 2018-11-28 10:41
I just tried it myself and it works as expected.
<img width="401" alt="bildschirmfoto 2018-11-28 um 11 38 39" src="https://user-images.githubusercontent.com/58428/49146416-684a8b00-f302-11e8-9787-8abdea9bc723.png">
<img width="274" alt="bildschirmfoto 2018-11-28 um 11 39 20" src="https://user-images.githubusercontent.com/58428/49146443-74364d00-f302-11e8-83ee-7307ef0c0b95.png">

Please keep in mind that "Auto-Type ausführen" (Perform Autotype) is not Global Autotype! To change the Global Autotype Shortcut you need to go to the Integration Preferences.
<img width="512" alt="bildschirmfoto 2018-11-28 um 11 36 11" src="https://user-images.githubusercontent.com/58428/49146188-e9555280-f301-11e8-879a-5fd54ee6f112.png">

**Comment by mstarke** [comment] 2018-11-28 10:42
Can you test if the Continous release has the bug for you or if it is fixed?

**Comment by LongPham0** [comment] 2020-08-11 06:19
Just tried adding 3 custom shortcuts via the mac default keyboard shortcut panel. It works after restarting macpass.
`Copy Username` is now set to `CMD + B` for example.

**Comment by JulianDoe** [comment] 2023-11-13 10:46
> I just tried to change the Autotype shortcut but it did not work. :-(
> 
> ![image](https://user-images.githubusercontent.com/458619/49145744-c37b7e00-f300-11e8-9a56-9c27063401a5.png)
> 
> Maybe the "ü" needs to be masked/escaped?

I'm facing the same issue. If I try to change the default shortcut of 'Adresse öffnen' via the system settings, it did not apply in Macpass  after restarting it(see also the screenshots). Even worse it does not apply the 'normal' shortcuts either.  
Is this a bug or is it me?

![grafik](https://github.com/MacPass/MacPass/assets/25430219/fac5ebe3-ac68-4b52-b9b7-9f7c1f8aa884)
![grafik](https://github.com/MacPass/MacPass/assets/25430219/29e879e4-badf-4ec5-b7c8-73cfa115bf92)

MacOS-Version: 14.1.1 (23B81)
MacPass-Version: 0.8.1 (26030)

**Comment by mstarke** [comment] 2023-11-13 14:52
I'm unable to reproduce this. The only real difference in my setup is that my system language is English not German.

![Screenshot 2023-11-13 at 15 51 07](https://github.com/MacPass/MacPass/assets/58428/75cb30e5-5430-4c7c-b672-1b359fcd855f)
![Screenshot 2023-11-13 at 15 50 58](https://github.com/MacPass/MacPass/assets/58428/b16405a3-7c0a-4e36-bc19-ad2f3895d7f8)

**Comment by JulianDoe** [comment] 2023-11-20 08:11
Sorry for the late repsonse.
I changed my system langauge from German to English but I have the same result (cf. Screenshots). So thats not the problem I guess. Maybe you can give some ideas where to search for other differences. 
![grafik](https://github.com/MacPass/MacPass/assets/25430219/8e119099-85bf-4999-836f-9d426be6cf37)
![grafik](https://github.com/MacPass/MacPass/assets/25430219/6f46a0e1-0c6f-4f2f-bbcb-43856a420fc0)

**Comment by mstarke** [comment] 2023-11-20 09:28
Late replys aren't a problem. Have you seen the lates release of MacPass ;-). So I'm in no position to be offended by delays. Another idea might be to remap a shortcut in another application and see if this works? I also suspect a conflict with another app that might take precedence for the `Cmd + B` shortcut. Or maybe use `Cmd + B` in another app as well and see if it sticks there?

**Comment by JulianDoe** [comment] 2023-12-06 07:16
So it finally works also on my machine. I can change the shortcut values, but only if they are not system defaults like `Cmd + C`. Maybe I oversaw (or read) something but it may help others which also struggle with this issue.
