### ISSUE TITLE
Autotype Password (Feature Request)

### ISSUE THREAD

**Issue by JamsheedMistri** [MacPass/MacPass#1131] opened 2021-01-04 01:19 UTC
**Describe the solution you'd like**
Sometimes I only want to Autotype my password, instead of the full Autotype sequence specified in each entry. For example, sometimes the username/password field is split among 2 pages instead of the normal 1, or sometimes the username field is pre-filled, in which case I would only want to type the password.

I would like a configurable keyboard shortcut that allows you to just autotype the password instead of the username/password combination specified.

**Describe alternatives you've considered**
The current alternative is opening MacPass, searching for the related entry, clicking the password field, and doing Cmd + C, which is significantly slower.

**Comment by mstarke** [comment] 2021-01-04 14:58
This is a duplicate of #974

**Closed by mstarke** 2021-01-04 14:58 UTC
