### ISSUE TITLE
Deleting a search result reloads the list

### ISSUE THREAD

**Issue by teemue** [MacPass/MacPass#1099] opened 2020-07-23 15:37 UTC
**Describe the bug**
Deleting an item from search results reloads the selected group and does not show remaining results. Search query stays in the search bar

**To Reproduce**
1. Search for something in a database
2. Delete single entry

**Expected behavior**
Remaining search results should be still visible.

**Desktop (please complete the following information):**
 - macOS: [e.g. 10.15.5]
 - Version [e.g. 0.7.12]

**Comment by mstarke** [comment] 2020-07-30 09:43
Nice finde. Search system needs a re-write so I cannot promise on the timeline for a fix.

**Comment by emikaadeo-git** [comment] 2021-01-27 20:25
Similar issue with version 0.8-beta (macOS 11.1)

1. Search for something in a database
2. Erase your search text from search field (ex. hit Escape)
3. Database list is missing

**Comment by mstarke** [comment] 2021-11-02 23:30
This is a duplicate of #721.

**Closed by mstarke** 2021-11-02 23:30 UTC
