### ISSUE TITLE
Search field gets disabled after searching once

### ISSUE THREAD

**Issue by abhishekb91** [MacPass/MacPass#1152] opened 2021-02-14 17:21 UTC
**Describe the bug**
The search field on top of the application "Search Everywhere" gets disabled after searching for an entry. This is also true, even if you click the "Search Everywhere" and click outside.
This However, does not affect the other functionalities, and I can still go to individual entries and copy username and password.

**To Reproduce**
1. Open MacPass
2. Select 'Search Everywhere' and search anything
3. Try to select the 'Search Everywhere' again; it will be disabled. The app works as normal, but one can't use the search bar anymore

**Expected behavior**
 The search bar should work all the time as expected 

**Screenshots**
1. Initial screen : <img width="1161" alt="Screen Shot 2021-02-14 at 12 09 10 PM" src="https://user-images.githubusercontent.com/11881672/107883690-5000bf80-6ebe-11eb-9fbf-4a52904cd823.png">
2. Searching in the "Search Everywhere": <img width="1161" alt="Screen Shot 2021-02-14 at 12 09 31 PM" src="https://user-images.githubusercontent.com/11881672/107883695-60b13580-6ebe-11eb-8c38-30d599278499.png">
3. Field gets disabled: 
<img width="1161" alt="Screen Shot 2021-02-14 at 12 09 51 PM" src="https://user-images.githubusercontent.com/11881672/107883725-8c342000-6ebe-11eb-9d9a-3cde1c6fdf7a.png">

**Desktop (please complete the following information):**
 - macOS: 11.2.1
 - Version 0.7.12
 - 2016 Macbook Pro 15"

**Comment by surmvoise** [comment] 2021-02-15 09:11
I experience that too:

- macOS 11.2
- Version 0.7.12
- iMac Pro (2017)

**Comment by mstarke** [comment] 2021-02-17 09:53
Known issue under Big Sur. Duplicate of #1113

**Closed by mstarke** 2021-02-17 09:53 UTC
