### ISSUE TITLE
Allowed Characters > Required Characters

### ISSUE THREAD

**Issue by Neo23x0** [MacPass/MacPass#831] opened 2018-09-25 07:10 UTC
The Password Generator offers a section of "Allowed Characters". 

However - in the real world - you usually have to match password requirements of an application or website. (e.g. Password has to contain: upper case, lower case, numbers, special characters)

And even if you don't have to match any password requirements, as a user you ought to see all character classes included. 
Why would you allow all character sets if a generated password could  result to be "agdicjla"?

I'd like to propose a change of the function so that "allowed" is changed to "required".

**Comment by mstarke** [comment] 2018-12-30 19:48
Duplicate of #731

**Closed by mstarke** 2018-12-30 19:48 UTC
Labels: Enhancement

**Comment by mstarke** [comment] 2019-01-31 15:11
Done in a7469975aded00b32b9a1fde9ad3aa16d998b25c. This is included in todays continuous build.

<img width="463" alt="screenshot 2019-01-31 at 16 10 04" src="https://user-images.githubusercontent.com/58428/52063324-b2562400-2572-11e9-8e88-92cccd88cef7.png">
